# fly.toml file generated for complain on 2022-12-03T23:28:22+01:00

app = "complain"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8000"
 
  DATABASE_DRIVER="asyncpg"
  DATABASE_HOST="complain-db.internal"
  DATABASE_PORT="5432"
  DATABASE_NAME="complain"
  DATABASE_USERNAME="postgres"
  DATABASE_PASSWORD="dpm8qDq0uYXd8ZI"
  SECRET_KEY = "32c44c8bc84cbb2e59d9f3a5775a8c425d69f145ccf0095d12e8672969cfdac9"
  ALGORITHM= "HS256"
  EXPIRY_TIME= 30


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
  
