"""test

Revision ID: d63403f4d1f9
Revises: dc585cc1c7eb
Create Date: 2022-11-08 15:00:34.978832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd63403f4d1f9'
down_revision = 'dc585cc1c7eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrecord', sa.Column('test', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userrecord', 'test')
    # ### end Alembic commands ###
